package com.example.procard.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF006D3D)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF84F8B5)
val OnPrimaryContainerLight = Color(0xFF002110)
val SecondaryLight = Color(0xFF4A6358)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCDE8DA)
val OnSecondaryContainerLight = Color(0xFF052019)
val TertiaryLight = Color(0xFF1F6077)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFBCE9FF)
val OnTertiaryContainerLight = Color(0xFF001F2A)
val NeutralLight = Color(0xFFFBFDF7)
val NeutralVariantLight = Color(0xFFE0E4DC)

val PrimaryDark = Color(0xFF67DB9B)
val OnPrimaryDark = Color(0xFF003821)
val PrimaryContainerDark = Color(0xFF005231)
val OnPrimaryContainerDark = Color(0xFF84F8B5)
val SecondaryDark = Color(0xFFB1CCBF)
val OnSecondaryDark = Color(0xFF1B352C)
val SecondaryContainerDark = Color(0xFF324B42)
val OnSecondaryContainerDark = Color(0xFFCDE8DA)
val TertiaryDark = Color(0xFFA1CEE4)
val OnTertiaryDark = Color(0xFF003544)
val TertiaryContainerDark = Color(0xFF014D5E)
val OnTertiaryContainerDark = Color(0xFFBCE9FF)
val NeutralDark = Color(0xFF111412)
val NeutralVariantDark = Color(0xFF444A43)